version: '3.7'
services:
  bot:
    image: geekbeacon/beacon-bot:${BOT_VERSION}
    restart: always
    build:
        context: . 
        dockerfile: docker/Dockerfile
    env_file: .env
#    volumes:
#     - ./:/app
  db:
    image: mysql:5.7.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    volumes:
        - ./sql:/docker-entrypoint-initdb.d
        - ./data:/var/lib/mysql 

